### PR TITLE
Fixnetcdf

### LINKED ISSUE #356: Error with py-netcdf4 1.2.1
MacPorts updated to py-netcdf4 1.2.1 (I had been on 1.1.9) and I'm getting the following error.

Context: Running the `mistis_setup` notebook. Problem occurs when opening the storage (cell 16). Traceback:

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-16-0f8af2293023> in <module>()
      1 #logging.config.fileConfig("debug_logging.conf", disable_existing_loggers=False)
----> 2 storage = paths.storage.Storage("mistis.nc", "w", template=template)

/Users/swensond/GoogleDrive/msm-tis/openpathsampling/storage/storage.pyc in __init__(self, filename, mode, template, units)
    143 
    144         self._template = template
--> 145         super(Storage, self).__init__(filename, mode, units=units)
    146 
    147     def _register_storages(self):

/Users/swensond/GoogleDrive/msm-tis/openpathsampling/storage/netcdfplus.pyc in __init__(self, filename, mode, units)
    218             self.create_dimension('scalar', 1)
    219 
--> 220             self._initialize()
    221 
    222             logger.info("Finished setting up netCDF file")

/Users/swensond/GoogleDrive/msm-tis/openpathsampling/storage/storage.pyc in _initialize(self)
    215         # update the units for dimensions from the template
    216         self.dimension_units.update(paths.tools.units_from_snapshot(template))
--> 217         self._init_storages()
    218 
    219         # TODO: Might not need to save topology

/Users/swensond/GoogleDrive/msm-tis/openpathsampling/storage/netcdfplus.pyc in _init_storages(self)
    326 
    327         for storage in self._objects.values():
--> 328             storage._init()
    329 
    330         self.update_delegates()

/Users/swensond/GoogleDrive/msm-tis/openpathsampling/storage/object_storage.pyc in _init(self)
    499             self.init_variable("name", 'str',
    500                                description='A name',
--> 501                                chunksizes=tuple([10240]))
    502 
    503         if self.json:

/Users/swensond/GoogleDrive/msm-tis/openpathsampling/storage/object_storage.pyc in init_variable(self, name, var_type, dimensions, **kwargs)
    570             var_type=var_type,
    571             dimensions=dimensions,
--> 572             **kwargs
    573         )
    574 

/Users/swensond/GoogleDrive/msm-tis/openpathsampling/storage/netcdfplus.pyc in create_variable(self, var_name, var_type, dimensions, description, chunksizes, simtk_unit, maskable)
    838         else:
    839             ncvar = ncfile.createVariable(var_name, nc_type, dimensions,
--> 840                                           zlib=False, chunksizes=chunksizes)
    841 
    842         setattr(ncvar, 'var_type', var_type)

netCDF4/_netCDF4.pyx in netCDF4._netCDF4.Dataset.createVariable (netCDF4/_netCDF4.c:16198)()

netCDF4/_netCDF4.pyx in netCDF4._netCDF4.Variable.__init__ (netCDF4/_netCDF4.c:26931)()

TypeError: illegal primitive data type, must be one of ['i8', 'f4', 'u8', 'i1', 'U1', 'S1', 'i2', 'u1', 'i4', 'u2', 'f8', 'u4'], got |S0
```

An error is also occurring when I run that with `ipynbtest`, but later (`mistis_calc is not defined` -- probably a case where the error happened earlier and `ipynbtest` missed it). Also happens in `teststorage.py` nosetest. 

I'm pretty sure the problem is with the netcdf update because it started just after I did the upgrade, stopped when I activated the older version, and started again when I activated the updated version, and stopped when I again reactivated the old version.

Using the old version is a temporary fix for me, but it's probably worth getting ready for when conda moves up to the new version.

### PR DESCRIPTION
**Pull request by jhprinz**
This could hopefully fix the update to netcdf 1.2.*

No sure, need to find a way to install it on my machine...

@dwhswenson Can you try and see, if that fixes it?

Resolves #356

### CODE REVIEW

**Comment by dwhswenson** [comment]
Will try, but probably not until later. In other words, don't wait up (any longer than you already have) for the response. ;-)

**Comment by dwhswenson** [comment]
Yep, that appears to do it! Shall I merge?

**Comment by jhprinz** [comment]
Great. Yes, please, since it does not affect the current version, too. It seems to be the future proof fix for now.

**Comment by dwhswenson** [comment]
Merging! (And updating to netCDF 1.2.1)

**Pull request merged**
