### PR TITLE
Rename

### PR DESCRIPTION
**Pull request by jhprinz**
Tried again

### CODE REVIEW

**Comment by jhprinz** [comment]
This should resolve Issue #153 for now until new things pop up :)

Ready for review and merge when it passes. Be careful though. This changes the LambdaVolume which is used in a lot of notebooks. It might be better to just not merge potentially changed notebook and fix this by hand.

**Comment by jhprinz** [comment]
Ready for review :) Merge whenever you think it makes sense. I will try to keep it mergeable when we add more PRs.

**Comment by dwhswenson** [comment]
My plan will be to merge this right after #268. I'd like to get the notebooks from that in before the major name change.

**Comment by jhprinz** [comment]
Sounds good. Let me know, I will probably have to fix it after merging #268 .

**Comment by jhprinz** [comment]
I will merge #281 first and then fix this and then adapt my other PRs.

**Comment by jhprinz** [comment]
alright. This is ready to be merged once it passes and #281 is merged.

**Comment by jhprinz** [comment]
Interesting. There was an API change in mdtraj topology. I need to fix that. Hmmpf.

**Comment by dwhswenson** [comment]
Any way to update it so that it is also compatible with older versions of MDTraj?

**Comment by jhprinz** [comment]
the problem is that the Element object which we store for the ToyDynamics needs now more parameters. Not sure if I can fix that. At least version 1.4.0 breaks.

**Comment by dwhswenson** [comment]
this would be a good place for a try-except ;-)

(Temporarily, until we can be sure that all our users are on more recent versions of mdtraj -- I'm personally running an older version, as is Peter, and I'd rather not deal with upgrading quite yet)

**Comment by jhprinz** [comment]
exactly. ;) That is what I am doing right now. try and otherwise try to use Elements with a radius.

**Comment by dwhswenson** [comment]
Now that this passes tests again, is it fully ready for review/merge?

**Comment by jhprinz** [comment]
This should be ready to merge. It is only renamings of some functions. It can be merged now or later but will need fixing again (I assume)

**Comment by dwhswenson** [comment]
Merging. Only comment is that we should consider the `move_scheme` name as it relates to the `MoveScheme` object in PR #285. One possibility is to rename the `move_decision_tree` in #285 as `move_scheme`. At first it seemed weird to me to say `MoveScheme.move_scheme`, but looking at examples (see new notebook in #285) it doesn't seem so weird.

**Pull request merged**
