### PR TITLE
Change .name storage

### PR DESCRIPTION
**Pull request by jhprinz**
This PR simplifies storage a little and add better support for the `.name` property.

All objects have now a special name property which can be set once before it is saved (we could actually change this).

There is also for all nameable objects a `.named(..)` function that creates a shallow copy with a new name. 

Instead of the decorator `@ops_object` there are new two base-classes `OPSObject` and `OPSNamed`.
Subclassing from these does the same as before in a easier to understand way.

The `.name` property is available for all elements as a string. Even if not set.

To be compatible with the only once setting of the name I had to remove the automatic setting of a name for `LambdaVolume`. I think the nice `min<op<max` output could be moved to either `__str__` or `.description`

### CODE REVIEW

**Comment by dwhswenson** [comment]
What is the reason for doing a ***shallow*** copy with a new name? I would assume that one might want a deep copy, if anything.

I think that the `min<op<max` should be set as the `name` by the `VolumeSet` thing that makes interfaces (that's where we really need this). This might also be an option of making that `description("short")` or something like that; I think that `description("long")` should be the current `__str__`, and `__str__` should be something like:

```python
if name is not None:
    return name
else:
    return self.description()
```

where I'm not sure if that should be `"short"` or `"long"`. But those changes are to be done much later in #233.

**Comment by jhprinz** [comment]
Important: Saving an unnamed object sets the name to an empty string. After that the name cannot be set anymore.

All objects that can be saved with name are
```
Volume()
Ensemble()
PathSimulation()
PathMover()
CollectiveVariables()
DynamicsEngine()
ShootingPointSelector()
Transition()
```

After tests pass, this should be ready to merge. 

Only question is if we want to keep the name only once policy. Not sure if this makes sense. It forces the user not to rename at will.

**Comment by jhprinz** [comment]
A deep copy would also make a copy of all contained stuff like ensembles, volumes and double the objects. That would be bad. A shallow copy only replicates the object and fills it with the same objects. There is one thing though and I need to check, if it correctly handles indices. See last commit.

I have not yet used the .named feature, we can also just use it to set the name. This still allows us to write it in a chain way
```
ens = Ensemble(...).named('myensemble')
```

**Comment by dwhswenson** [comment]
1. I think "objects-immutable-after-saving" is a fair rule to play by. Mutable until saving is what matters to me.

2. Now I see the chain approach, and that's not bad. But without that, I think `object.name=myname` is better than `object.named(myname)`, esp. since the latter creates a copy (which means references to it won't be the same, so it is NOT the same as setting the attribute, right?). I could imagine someone wanting to create a deep copy with a new name and modify it; that's why I'm concerned this might be confusing.

2. I think it might be nice to have a `default_name` function, or at the least have it default to the class name, rather than the empty string. I suppose some of that can be achieved in most cases by doing `if self.name == "":` in the `__str__`, which is, I think, where we'll usually want to access the name. But a non-trivial default might be good to have.

**Comment by jhprinz** [comment]
1. Mutable until saving might require an additional flag to carry around. Setting a name once does not, which makes the code a little clearer, but I agree that it is not so common in python

2. Exactly, using `.named(myname)` will be different from `.name = myname`. The first will clone the object which is equal to call the constructor with the same parameters, so both objects represent the same information/are identical, but are not one and the same. This is the idea of functional programming and I agree that might be too much. The upside is flexibility (which is what we want), the downside is that a user can do something that is not wanted or reasonable at an arbitrary point in the code and sometime later your code crashes and you do not know why. This is of course the extreme case. 

An example: One of your tests is testpathmover sets the name of an object to 'stateA' and will check for/search for it later. That code is hidden and noch accessible to the user. At a later stage you change the name for convenience and all references change with it. When you do the testing you cannot find your object. This is - I agree - very constructed - but the point is that if you create an object with properties and can depend on that object being immutable you know where to find an error, because there is only one place where the variable could be set.

This should only be an explanation why I like this approach so much. The little overhead for constructing a shallow copy is negligible is most cases (if the compiler or interpreter is smart). Anyway, I think this is in this particular case not really necessary, also because the name is more for convenience and will not destroy a calculation if fiddled around with.

I also agree that this approach is not so well known and might be confusing. Especially because of this:
```
x = MyObject()
x.named('test')
print x.name
>>> None # x did not have a name and it is immutable
y = x.named('test')
print y.name
>>> 'test' # this works
```

This concept of _chaining_ is often used in javascript and requires each setter to return the object itself.
This confusion would be my reason not to use it.

3. Good idea. I would call it a `default_name` property and return the result, if the `._name` is empty automatically like
```
@property
def name(self):
    if self._has_name or self._name is '':
        return self._name
    else:
        return self.default_name
```

4. I will change the code so that you can change it as long as you want. Empty string means use default and we save the empty string so the default name will adopt to changes in `.default_name`

**Comment by jhprinz** [comment]
I added a flag to make sure you cannot change the name after storage.

Concerning the searching by name: This will only look for really manually set names, not for the default_name which I think makes sense.

**Comment by jhprinz** [comment]
Finally, searching by name works again, with the following caveats.

1. You can only load by a set name not by a default name
2. If there are more than one object with the same name you get the first one (no errors thrown, but it is mentioned in the logger)
3. `storage.[object].find(name)` searches for all objects of a name
4. `storage.[object].find_first(name)` searches for the first object of a name
5. `storage.[object].find_indices(name)` returns indices for all objects of a name

Usually there should be only one object of a given name, but who knows. With this PR you can now use

```
# save
my_retis = RETISTransition().named('myRetis') #give it a name
my_retis.name = 'myRetisTransition' # change name afterwards

storage.save(my_retis)

# and load
storage.transitions.save(my_retis)
retis = storage.transitions['myRetisTransition']
```

**Comment by jhprinz** [comment]
fixed the storage tutorial to work with name and not uid.

Should be ready for review and merge!

**Comment by dwhswenson** [comment]
When I say "mutable until save", I really mean "mutable until production; save at production". Saving the setup is the first step in production.

Here's a realistic usage that should be allowed:

```python
mstis = MSTISNetwork([
    (stateA, interfacesA, "A", opA),
    (stateB, interfacesB, "B", opB)
])
outermostA = mstis.from_state[stateA].ensembles[-1]
# MSTISNetwork gives reasonable standard names, so that, for some min and max:
# "min<opA<max" == outermostA.name

outermostA.name = "outermostA"
# changing that standard name to a custom name
```

(Terminology: I'm using "standard name" to refer to a name set computationally by another part of the program without user interference; this is to distinguish from "default name" which is set by the object itself or "custom name" which is set by the user.)

Three points that I think need to be handled:

* We absolutely do NOT want a copy here, because the ensemble is in a context of `PathMover`s etc which would also all have to be changed. 
* We do not want the user to have to lose all the conveniences that come from the `MSTISNetwork` object, just because s/he wants to give a custom name to one part of it.
* We want the `MSTISNetwork` object to be able to assign standard names based on the context that it understands, since those standard names will be good enough for most users.

As the code stands now, is all of that supported?

**Comment by jhprinz** [comment]
Quick answer for your 3 points. 
- agreed, no copies. The idea of making a renamed copy is only meant to be used when creating the object, this is why you should the `.named` ONLY in chain. And that is too dangerous. So I removed all of the copying and it does what you proposed
- also agreed, the MSTISNetwork, etc is the center of the calculation this must be one object. And it is, no changes here, too.
- Yes, it can assign standard names. If it does not the `.default_name` property will be used to generate a name. This `.default_name` is always computed and will not be stored. This means you need to be aware of what you get when using a name of one object to build the name of another. You might have to assign names in the correct order! The user can now always change the names as he wants unless the objects are stored, which is done by starting the simulation or manually by the user. You will get an error message in that case.

So, I think it should be what we wanted, right? Sorry, for my immutable excurse... 

Will fix the merge issue now.

**Comment by dwhswenson** [comment]
You changed the `toy_tis` notebook to outputting `toy_retis.nc` instead of `_toy_retis.nc`. You'll need to change that in the `repex_networks` notebook too.

**Comment by jhprinz** [comment]
Ups, yes I thought that was a mistake of mine. Sorry, which one do you need? With or without the leading  underscore?

**Comment by jhprinz** [comment]
Actually, I thought I had fixed that. I guess the last merge messed that up :)

**Comment by dwhswenson** [comment]
Doesn't matter: I switched it at some point to keep some 10k MC step results around. The main thing is that `toy_tis` has to generate something, and `toy_analysis` and `repex_networks` need to use the same thing after ... `toy_analysis` still needs to be added to tests (but not yet -- WHAM chokes if the data is insufficient)

**Comment by jhprinz** [comment]
okay, so I move all of them (also visualization) to `_toy_retis.nc`. Just a second

**Comment by dwhswenson** [comment]
I think you made the changes in the wrong branch.

**Comment by jhprinz** [comment]
Yup. I did...

**Comment by jhprinz** [comment]
Woohoo... Travis passes. That is a good sign...

**Comment by dwhswenson** [comment]
Merging!

**Pull request merged**
