### PR TITLE
Move ipynbtest to external package

### PR DESCRIPTION
**Pull request by jhprinz**
This moves the ipynbtest to a separate project / package and installs it using conda.

### CODE REVIEW

**Comment by jhprinz** [comment]
I moved the testing script to [ipynb-test](https://github.com/jhprinz/ipynb-test) and made it conda installable. There is still be problem, that I need a new working Anaconda TOKEN to make this automatically. So far I uploaded a recent version directly to anaconda.

You can now simple use
```
conda install ipynbtest
```
when omnia is in your package channels. After that just run
```
ipynbtest.py -h
```
to see the help. I hope that this way we can keep updating this much more clean.

**Comment by jhprinz** [comment]
This will also resolve issue #362. Problem was that a cell with no output stored in the notebook would not be tested. This is corrected now. The updated ipynbtest has a few additional features.
1. `--abort-if-fail` will stop the test after the first cell fails. This will improve speed when checking if all tests pass without knowing exactly which ones.
2. `--eval [CODE]` will run the CODE before the first cell is run. This way you can set some variables for specific cases, number of samples, etc...

**Comment by dwhswenson** [comment]
Great! Let me know when these changes are ready to merge. I have every expectation/intention of using this in many non-OPS projects. I've already starred, watched, and forked the repo. :-)

**Comment by jhprinz** [comment]
Yeah, my first star... :)

**Comment by jhprinz** [comment]
I think this is ready for review and merge. We can make updates in the external repo and then I can upload the new version to anaconda.

All this does is install the ipynbtest package and remove unnecessary files.

**Pull request merged**
