### PR TITLE
Alanine dipeptide TPS examples

### PR DESCRIPTION
**Pull request by dwhswenson**
This PR will include code for both of our alanine dipeptide TPS examples: fixed length and flexible length.

Five new files. To reproduce results, run them in order:

* `alanine_dipeptide_tps_first_traj.ipynb`: getting the first trajectory satisfying the flexible path length TPS approach
* `alanine_dipeptide_tps.ipynb`: TPS for the flexible path length version
* `alanine_dipeptide_fixed_tps_first_traj.ipynb`: Obtaining the first trajectory for the fixed path length TPS
* `alanine_dipeptide_fixed_tps.ipynb`: TPS for the fixed path length version
* `alanine_dipeptide_tps_analysis.ipynb`: Combined analysis file for fixed and flexible path length TPS.

- [x] Get initial trajectory for AD example from hi temp
- [x] Equilibrate in low temp path ensemble
- [x] Run long flexible path length simulation
- [x] Get fixed path length traj from flexible sim
- [x] Run long fixed path length simulation
- [x] Analysis
- [x] Update ipynb directory readme

Includes parts of #481

### CODE REVIEW

**Comment by dwhswenson** [comment]
Also, I recommend taking a look at the way I set up the high-temperature trajectory in `alanine_dipeptide_tps_first_traj.ipynb`. It's a nice trick using our ensembles to simplify the process. It would work just as well for multiple states -- I think we should modify the AD MSTIS example to use a similar approach.

**Comment by dwhswenson** [comment]
A little update on this: the most recent commit includes the notebooks for the 10000-shooting-move flexible path length TPS on alanine dipeptide, along with analysis of the path length distribution and  a partial path tree. (Thanks @jhprinz for figuring out and fixing the dynamics error yesterday!)

Today I'll start running the fixed path length TPS. I needed the results from flexible path length to know a good path length to use. I'll use 8 ps (400 frames), which is a little longer than the max length found by the flexible path length simulation. This also gives a little room for the transition path to diffuse along time coordinate, since we don't have shifting. I'll only run 1000 shooting moves for the fixed path length.

I don't include the output file from the flexible path length simulation, since it is over 17GB. No reason to put that in the repository. If anyone is really interested, I'll send you a link to it (it is currently in my Dropbox).

**Comment by dwhswenson** [comment]
Working fixed-length TPS as well, with some preliminary analysis. I plan to do a little more analysis tomorrow, but the heart of the example is already done.

**Comment by jchodera** [comment]
Cool!

Some comments:
* Are all the IPython examples just dumped in `examples/ipython/` without any subdirectory organization?  What would you think about organizing things by example, like `examples/alanine dipeptide/`?
* The notebooks all seem to be pretty empty. Are there supposed to be figures?
* Can you write a `README.md` indexing what you have?  The filenames are pretty uninformative.
* Why not have the filenames be more informative, like `alanine dipeptide TPS with fixed-length path.ipynb`?
* We presumably need some commentary in the notebooks describing what is being done. There aren't even comments---only section headings.

**Comment by jhprinz** [comment]
Thanks David!

I like the idea of subdirectories. The examples section really could use some cleanup. There should be a README.md file that lists all the existing notebooks and what they contain. When we break this up into subdirectories we will split the README.md as well.

More detailed naming. Why not. Can't hurt and times of a 40 character limit are long gone...

There should be lots of comments in the notebooks. Some of the tests I think do not have comments. The examples should. If its missing that this is still a TODO.

The split into several notebooks is to better separate the main steps. Like chapters in a book. It will also keep the notebooks reasonably small.

**Comment by dwhswenson** [comment]
So, a little context here: @bolhuis is *very* eager for me to finish the examples PR I'm writing in the manuscripts repo. I don't feel like I can really write about the examples until I actually do them -- how else can I make sure I didn't leave out any steps? So that's what this PR is about. It's an attempt to get this done rapidly.

To @jchodera's comments:

> Are all the IPython examples just dumped in examples/ipython/ without any subdirectory organization?

Currently, yes. But here's the issue I was going to submit (already drafted) immediately after finishing this PR:

***
ISSUE: Reorganize examples/

I think the examples directory has gotten a little out of hand. This is probably a good thing: It means that we have lots of examples to share. However, it makes it harder and harder to find the examples that are actually relevant.

I suggest we reorganize the directories a bit. First off, I propose dropping the idea of an `ipython` directory within the `examples` directory: all our examples are IPython notebooks.

I’m thinking something along the lines of the following:

```
examples/
|- alanine_dipeptide/
|  |* alanine_solvated.pdb
|  |- tps/
|  |  |* alanine_dipeptide_tps_first_traj.ipynb
|  |  |* alanine_dipeptide_tps.ipynb
|  |  | . . . etc
|  |- mstis/
|- mstis_toy_model/
|- mistis_toy_model/
|- tests/
|- miscellaneous/
```

@jhprinz, I wanted your feedback before such a reorganization, but once we decide on a good directory structure, I can spend an evening typing `git mv` and reorganizing the `README.md` files.
***

It sounds like we’re all in agreement that a reorganization should happen! @jhprinz, if you’d like, I can do that as part of this PR.

More details on what I was proposing there:

A key point is that each of what I've been calling our "sequences" should be in a separate directory. When I say "sequence" here I mean the group of example notebooks that should be run in a specific order; to enlarge @jhprinz's analogy, if each notebook is a "chapter", then each sequence is a "book", and the whole set of examples is a "series." (Or maybe you would say each sequence in a "part" in the overall "book" -- if the book was written by Tolstoy.)

The `tests` subdir would include the things that are specifically tests (other than the examples) and the `miscellaneous` subdir would include other files; mostly stuff listed under `tutorials` in the current README.

It might be worth splitting some of the `miscellaneous` out in a more clear manner; the stuff between the horizontal rules above was all a draft that I was going to put more thought into after this PR. But the main idea I feel strongly about is that our example "sequences" should each have their own subdirectory.

> The notebooks all seem to be pretty empty. Are there supposed to be figures?

The `*_first_traj` notebooks are designed to get a first trajectory. In the flexible-length version, there's a figure showing the trajectory. I'm not sure what other figures you would want. The fixed-length version doesn't have any figures because it's just a quick and dirty way of getting an initial path that satisfies the desired ensemble, based on the first path that satisfies the flexible path length ensemble. I don't think there's a better way to get that initial path, at least, not if we’re not using shifting moves, but I don't think that's particularly pretty. I could add a figure similar to that in the flexible-length of the final trajectory, if you think that's important.

The `*_run` notebooks don't contain any figures. In principle, they should show the "live visualization" figures while running, but something seems to have changed in Jupyter, and that stuff behaves differently (although you'll notice text claiming a matplotlib figure). It's on my "fix soon" list, but after this PR. In any case, these are the things that you run on a separate machine, possibly for days when doing big systems. I don't think anyone expects figures out of this -- in the real world, you would export the Python and submit it to a compute node -- not run it interactively.

The `analysis` notebook is the main place for results, so it’s also the main place to look for figures. It contains path tree diagrams (which need to be updated with @jhprinz's work in #400 when that's done) for both flexible and fixed length, and the path length distribution for the flexible length. In addition, it includes lots of results in text that can't be figures: acceptance rate for the shooting move, number of decorrelated trajectories, stats about the path length distribution for flexible paths (max length, mean length). I’m planning to add more analysis tools later, which will lead to more figures (in particular, I’d like to add a path density plotting tool, but *after* this PR -- then we could plot a couple representative trajectories on top of the path density).

What other figures would you want? You can see a few things I was thinking about from the comments in the `analysis` notebook. I probably won’t add all of those, but if there’s something you’d really like to see (either listed there or not), let me know.

> Can you write a README.md indexing what you have? The filenames are pretty uninformative.

This is the last task in this PR's task list: "Update ipynb directory readme". Unless you mean that the [current version](https://github.com/choderalab/openpathsampling/blob/master/examples/ipython/README.md) is unclear for files existing prior to this PR, in which case, please let me know where the problems are and I’ll try to improve it!

> Why not have the filenames be more informative, like `alanine dipeptide TPS with fixed-length path.ipynb`?

If we have to make the file name long to be informative, then I think we’re doing something wrong. Personally, I work in an 80-column terminal. So i *am* opposed to long file names. (And don’t get me started on spaces: escaping them is an absolute pain if you’re dealing with a mixture of shell and URI-based approaches. Let’s stick to the POSIX-portable filename character set.)

That said, I think we can make the filenames clearer. If we redo the file structure, then `alanine_dipeptide` is redundant, since it is already in the file path. So we can abbreviate `alanine_dipeptide` as `AD`. How about roots of `AD_fixed_length_tps` and `AD_flex_length_tps` with suffixes of `_initial` (or `_setup`?) and `_run`? The analysis notebook combines both analyses, so `AD_tps_analysis`. If a user can't tell what is going on from that, then they need to look at the `README.md`, which will also be in that directory. If you know roughly what to expect, I think those filenames are clear, and there’s always a README to fall back on if they aren’t.

> We presumably need some commentary in the notebooks describing what is being done. There aren't even comments---only section headings.

This is intended to be a rapid development first draft. My plan was to write the code here, then write short descriptions in the manuscript. You can already see that in progress in my PR on the manuscripts repo. There's a full page of text just describing the analysis. As I mentioned above, @bolhuis wants the manuscript stuff done ASAP. When that's done, I thought I'd come back and write a slightly expanded version of the manuscript commentary in the notebooks.

Also, my assumption has been that people will read the toy example notebooks first. Now that we have a lot of examples for both the toy models and alanine dipeptide, I’d appreciate some other perspectives on what order you think people would read things. (Personally, I’d start with the most simple models, and build up to more complicated things. But despite my time in chemistry departments, I’m a physicist at heart, so maybe others would try a different path. We should be trying to make all paths as easy as possible.)

> Why are there so many IPython notebooks? Don't we want one notebook for each example?

I strongly disagree with this premise.

A few points:
* for the purpose of showing how to do path sampling, *it doesn't matter* how you got the first trajectory: I don’t want users to come out of this thinking that running high temperature is a step in the process called path sampling
* depending on the system and the tools you have available, different approaches to the first trajectory are best
* the approach we use, with high temperature trajectories, is *not* the one we would generally consider to be best -- but it is good enough for alanine dipeptide.

I’m trying to make the TPS examples to focus on TPS. The `run` notebooks are really short, because once you have a transition trajectory, we've made TPS really easy. That's should be the take-home message from those notebooks.

The `first_traj` notebooks here (and similar notebooks with suffixes like `_setup` in other examples) are mainly to get those first trajectories. They are often as long as the path sampling notebook, and must be done first. If you start with those, people are left very confused about what is actually path sampling. To me, path sampling doesn't start until you have a trajectory. I don't care how you got that trajectory: getting it is not part of path sampling.

The analysis is always in a separate notebook, because in real life, it's usually done separately. You create the data, then you analyze it.

One thing that I think we need to do better in these notebooks is to make it clear what the prerequisites and subsequent notebooks are. In this PR, the sequence goes:

* `_tps_first_traj` -- Requires: nothing; Next: `_fixed_tps_first_traj` for fixed length, or `_tps_run` for flexible 
* `_tps_run` -- Requires: `_tps_first_traj`; Next: `_analysis`
* `_fixed_tps_first_traj` -- Requires: `_tps_first_traj`; Next: `_fixed_tps_run`
* `_fixed_tps_run` -- Requires: `_fixed_tps_first_traj`; Next: `_analysis`
* `_analysis` -- Requires: `tps_run`, `_fixed_tps_run`; Next: nothing.

Most of our sequences don't have this combined analysis, so while they might branch out from a common starting point, they don't rejoin later. In any case, I think we should add a sentence at the beginning of each notebook ("In order to run this, you'll need the file `$filename`, which is generated in notebook `$previous_notebook`") and at the end of any notebook that has been completed ("Now that this has run, you can go on to doing `$next_task` in the notebook `$next_notebook`"). The README already information to show the order, but the notebooks should, too.

**Comment by dwhswenson** [comment]
> The `*_run` notebooks don't contain any figures. In principle, they should show the "live visualization" figures while running, but something seems to have changed in Jupyter, and that stuff behaves differently (although you'll notice text claiming a matplotlib figure)

The run scripts don't have a `%matplotlib inline` magic. I bet that's the problem with them.

Still not sure why the `first_traj` script shows *all* figures in its output... It shows them one at a time (as it should) until it ends, then spits them all into one output.

**Comment by jchodera** [comment]
> Currently, yes. But here's the issue I was going to submit (already drafted) immediately after finishing this PR

It sounds like you'd like to just merge this partial PR and move right to the next PR then?  If so, then we can just discuss in that PR.

**Comment by dwhswenson** [comment]
> It sounds like you'd like to just merge this partial PR and move right to the next PR then? If so, then we can just discuss in that PR.

Basically yes, although on that specific point (reorg of examples), I was actually going to post an issue for discussion, to get @jhprinz's feedback before doing anything. It's also reasonable to get that feedback in here and toss it in as part of this PR. (I mean, once we agree on the directory structure, it's the sort of thing I can implement while watching tonight's Game of Thrones.)

**Comment by jchodera** [comment]
### Examples directory reorganization
You propose:
```
examples/
|- alanine_dipeptide/
|  |* alanine_solvated.pdb
|  |- tps/
|  |  |* alanine_dipeptide_tps_first_traj.ipynb
|  |  |* alanine_dipeptide_tps.ipynb
|  |  | . . . etc
|  |- mstis/
|- mstis_toy_model/
|- mistis_toy_model/
|- tests/
|- miscellaneous/
```
Some observations:
* Why use `under_strike` naming? Modern filesystems support spaces. They're great for clarity.
* I wouldn't keep random files like `alanine_solvated.pdb` that the user doesn't need to *read* or *run* in the basic example directories. Think like a user: When you `cd` into a directory, what do you want to see? Only stuff that you will read or run. Put everything else into informatively-named subdirectories, like `input-structures/` or `system/` or something.
* Where are the `README.md` files in here? These are, without a doubt, **the most important part**. Every directory should have a `README.md` telling you what the directory you are in is for, what files are there and what they do, and what is in the subdirectories.
* Why did you choose to put `alanine_dipeptide` at the top level and then `mstis` underneath? Again, think like a user: What will a user be looking for when they go searching? Suppose they are looking for an example of MSTIS they can play with. Are they going to want to search into every system *type* directory for a subdirectory called `mstis`?  Probably not. Would they look in `mstis` and then be happy to find either a toy model or an molecular system?  That sounds more reasonable.

**Comment by jchodera** [comment]
### Notebook figures
>> The notebooks all seem to be pretty empty. Are there supposed to be figures?
> The *_first_traj notebooks are designed to get a first trajectory. In the flexible-length version, there's a figure showing the trajectory. I'm not sure what other figures you would want. 

Again, think like a user: If you look into a notebook and just see a block of undocumented code without comments or description, what are you going to do? Never look at the damned thing again, and not bother figuring it out. We need to give them *something* here. There must be *some* way you can summarize what the hell is going on in the notebook with figures or some output text. If it's an alanine dipeptide, show a picture of alanine dipeptide at the top. If it generates a trajectory, project the resulting trajectory it onto `(phi,psi)`. If it generates a bunch of flexible-length trajectories, maybe show the projections of those. Surely you can think of *something* that would be of interest just to give the user a quick graphical idea of what went on in each block of code.

> The fixed-length version doesn't have any figures because it's just a quick and dirty way of getting an initial path that satisfies the desired ensemble, based on the first path that satisfies the flexible path length ensemble. 

So just plot a `(phi,psi)` projection of the generated path?

> I don't think there's a better way to get that initial path, at least, not if we’re not using shifting moves, but I don't think that's particularly pretty. I could add a figure similar to that in the flexible-length of the final trajectory, if you think that's important.

I don't think we should be too worried about how you generate that initial path.

> The *_run notebooks don't contain any figures. In principle, they should show the "live visualization" figures while running, but something seems to have changed in Jupyter, and that stuff behaves differently (although you'll notice text claiming a matplotlib figure). It's on my "fix soon" list, but after this PR. In any case, these are the things that you run on a separate machine, possibly for days when doing big systems. I don't think anyone expects figures out of this -- in the real world, you would export the Python and submit it to a compute node -- not run it interactively.

Are these example notebooks going to require the user run them for days? If so, we're fucked---nobody will ever use the thing, because nobody has the patience to run something for more than a couple of minutes. Also, we won't be able to test anything on travis because we only have a couple of minutes to spend on each notebook.

I really think that the notebooks should be complete stories: Fully annotated examples that provide more detail about the examples in the paper. Obviously, the user version of the notebook we expect people to run out of the box would only run for a couple of minutes. The version of code that is run for the paper would be run long enough to generate nice statistics, and may not even be a notebook---one should arguably never be running a notebook of anything that takes more than a few minutes, since it requires all sorts of interactive connections to be maintained.

I very much disagree that we should split notebooks into many pieces. As you say, think of a notebook like a chapter or major section of a book: It should tell a self-contained story. Having it fragmented into lots of notebooks meant to be run in a certain order is a quick way to turn off your audience and have them quickly lose interest in your tool.

**Comment by jchodera** [comment]
Also, I wouldn't really stress much about the first-trajectory issue not being optimal. That's totally fine, and people will understand there are better ways if you note this in the comments about how you get the first trajectory.

In fact, if you want to wrap the poor-man's first-trajectory generator into a utility function somewhere and call it because it is embarrassing, you can do that and be done with it---you then just have to mention that you are using a very crude suboptimal method to get a first trajectory, call it, plot the trajectory, and move on.

**Comment by dwhswenson** [comment]
> Why use under_strike naming? Modern filesystems support spaces. They're great for clarity.

As I said above, escaping them is a pain if you're working with mixtures of URIs and shell. This is part of my workflow. I have a custom URI that opens a given file in my text editor. I can put a link to the relevant file in a to-do item in my to-do list manager, and with a click of the mouse, I'm editing. I was thinking of doing a similar thing with an ipynb URI. Some of my even fancier workflow stuff (where I've been known to toss some AppleScript into the mix) makes properly escaping spaces becomes nearly impossible.

They're also really obnoxious to escape when I'm working in terminal, which is where I always work. Spaces in filenames are absolutely one of my pet peeves. Let's stick with the POSIX portable filename character set.

> I wouldn't keep random files like alanine_solvated.pdb that the user doesn't need to read or run in the basic example directories

Sure, that works.

> Where are the README.md files in here?

Sorry, I thought the "every directory has a README" was implicit. In fact, I'm pretty sure I wrote the words "reorganizing the README.md files" which I think makes it explicit.

> Why did you choose to put alanine_dipeptide at the top level and then mstis underneath?

Because some of these methods are part of a sequence.

Example: SRTIS takes the same setup input as MSTIS. My plan was to put SRTIS with MSTIS. How would you suggest organizing that?

**Comment by jchodera** [comment]
> Because some of these methods are part of a sequence.
> Example: SRTIS takes the same setup input as MSTIS. My plan was to put SRTIS with MSTIS. How would you suggest organizing that?

How do we envision users actually using these things? Do they have to go through all the notebooks in a sequence in order?  Or would they just want to find an example of the method they are interested in and start tweaking it?

**Comment by dwhswenson** [comment]
> Again, think like a user: If you look into a notebook and just see a block of undocumented code without comments or description, what are you going to do? Never look at the damned thing again, and not bother figuring it out. 

Let me reiterate points from my (admittedly long) [post](https://github.com/choderalab/openpathsampling/pull/482#issuecomment-220838271):

* This PR is still incomplete. (Note the two unfinished tasks.) Furthermore, I'm only aiming for a DRAFT here.
* I mentioned that I was planning to come back to write descriptions
* Significant descriptions are already in https://github.com/choderalab/pathsampling-manuscripts/pull/17

> If it generates a trajectory, project the resulting trajectory it onto (phi,psi). 

This is in the `alanine_dipeptide_tps_first_traj.ipynb` notebook.

> So just plot a (phi,psi) projection of the generated path?

Yes, that's what I suggested in last sentence of that paragraph.

> Are these example notebooks going to require the user run them for days? If so, we're fucked---nobody will ever use the thing, because nobody has the patience to run something for more than a couple of minutes

1. **Then why aren't we focusing on the toy models?** That's why I wrote them up in the first place. The purpose of the toy models was to have interactive examples. They run much faster. Meaningful results from alanine dipeptide will take hours with TPS, probably days with TIS (if running on a desktop-class GPU). Compare that to minutes/hours with the 2D toy models. They also already contain lots and lots of figures and lots and lots of commentary. What I was trying to do here was the work we'll publish in the paper. As I mentioned several times, Peter wants me writing up the examples section of the paper. These notebooks are the examples section of the paper.

2. **Please read what I wrote.** In what you quoted, I said, "In any case, these are the things that you run on a separate machine, possibly for days when doing big systems". Your response is about the examples. Do we have "big systems" in the examples? I'm talking about things like kinases. You certainly don't expect meaningful results on systems of that size in less than days of simulation!

> I very much disagree that we should split notebooks into many pieces.

Yes, and nothing is going to change either of our opinions on this. I don't like the one-pot-cooking approach because it doesn't represent a realistic workflow. You want everything to be in one notebook. We both have good reasons, but different priorities.

> How do we envision users actually using these things? Do they have to go through all the notebooks in a sequence in order? Or would they just want to find an example of the method they are interested in and start tweaking it?

Well, that was the question I was getting at when I wrote:

> Now that we have a lot of examples for both the toy models and alanine dipeptide, I’d appreciate some other perspectives on what order you think people would read things.

My suggestion is to do exactly what I'd expect from a book on a scientific or mathematical topic. There is an expected order to read it in. However, a reasonably advanced reader should be able to skip to any chapter and get the important details of that chapter, and the chapters should assist such a reader by having references back to concepts taught earlier (including where).

For the order, I would suggest:

Volume I: Basic concepts (toy models). Contents: 1. TPS (1a. Flexible length; 1b. Fixed length); 2. MSTIS (2a. Multiple replica; 2b. Single replica) 3. MISTIS. 
Volume II: Practical issues of real systems (alanine dipeptide). Contents: 1. TPS (1a. Flexible length; 1b. Fixed length); 2. MSTIS (2a. Multiple replica; 2b. Single replica).

[Aside: I think it makes sense to combine the SRTIS and MSTIS examples as much as possible. They differ by (a) one line difference in move scheme (b) it's easier to get "all" the SRTIS initial trajectories (only one).]

**Comment by jchodera** [comment]
Your original post was TL;DR, so it should be unsurprising that it wasn't read in its entirety.

Do you really want to treat your notebooks like a textbook? That may be valuable for teaching a course, but I think it's going to create an impediment to allowing people to jump in and get started with their systems, resulting in low user rates and difficulty in getting any sort of long-term funding to sustain this effort.

**Comment by jchodera** [comment]
> What I was trying to do here was the work we'll publish in the paper. As I mentioned several times, Peter wants me writing up the examples section of the paper. These notebooks are the examples section of the paper.

Perhaps they shouldn't be notebooks, then. Perhaps you should just have some Python code and a script to run them in the appropriate sequence. Given what you have here, putting the code in notebook format adds nothing of value, and in fact makes it harder to run due to the interactivity requirements.

**Comment by dwhswenson** [comment]
> Your original post was TL;DR, so it should be unsurprising that it wasn't read in its entirety.

I'm not surprised you didn't read all my words; I'm just surprised you didn't read the words you quoted, and then responded to words that weren't there.

> Do you really want to treat your notebooks like a textbook? That may be valuable for teaching a course, but I think it's going to create an impediment to allowing people to jump in and get started with their systems, resulting in low user rates and difficulty in getting any sort of long-term funding to sustain this effort.

Well, I'm thinking more like advanced topics books, where I typically need to figure out one subset of the total field but 90% of the book is irrelevant to me. There's one chapter that I need, but that chapter may have background in other chapters.

Maybe a better example is a user manual. Or, say, any O'Reilly book. I've got the [Cython book](http://shop.oreilly.com/product/0636920033431.do) here -- now, if I really want to understand Cython, I would read each chapter in order. In practice, what I actually did was jump straight to the example chapter that was most relevant to my interests. But then, I needed to be ready to go back earlier chapters to understand some basic material I'd skipped. And the uninteresting grunt parts (Cython: compiling; OPS: first trajectory) is in a separate chapter that I only bothered reading when I actually needed it. There's a reason the O'Reilly books are so popular among programmers: they make it easy to get up and running in a new environment. Isn't that what we're aiming for?

**Question**: *Do you think that we should repeat the same commentary over and over in every example?* There's a case to be made for this, in that it makes every example independent. That seems to be what you want. However, I feel that the case against it, which is that you drown the differences under the similarity, is a stronger one. That's why I thought that the examples should have a brief "we do this, the same way we did in this earlier example" statement for things that have already been done.

This is particularly relevant if we have similar methods for both toy models and alanine dipeptide. When @jhprinz made the alanine dipeptide MSTIS examples, he largely copied commentary from my toy model version. I assumed we would re-write the AD commentary to emphasize aspects of differences and similarities -- setup stuff, in particular, is different, but it is useful to emphasize how much the same the actual MSTIS network, move scheme, and path sampler setup are. I thought that would have much more value for our users.

> Perhaps they shouldn't be notebooks, then. Perhaps you should just have some Python code and a script to run them in the appropriate sequence. Given what you have here, putting the code in notebook format adds nothing of value, and in fact makes it harder to run due to the interactivity requirements.

So we drop all the alanine dipeptide notebook examples (except analysis)? I'm fine with that. I was only making them into notebooks because I thought we were planning to have notebooks that users could use to re-run the examples that we put in the paper. If that's not a goal, then I misunderstood.

But it seems like your actual complaints are about two things that are strongly related to the fact that this is an early draft:

1. *more discussion*: I've already said it several times today: **Discussion is in the PR for the paper already; I was planning to come back to add an extended version of that to these notebooks later**
2. *runs too long*: Run the toy model if you want good results quickly. Change the number of steps to something smaller in alanine dipeptide if you want bad results quickly. What I've been doing is for the paper, where I assume we want good results on alanine dipeptide. That doesn't happen so quickly.

**Comment by dwhswenson** [comment]
>> Your original post was TL;DR, so it should be unsurprising that it wasn't read in its entirety.

> I'm not surprised you didn't read all my words; I'm just surprised you didn't read the words you quoted, and then responded to words that weren't there.

This wasn't fair of me. I felt like you were taking a jab at me, and so I took a jab back. I apologize for that.

Yesterday, you asked a bunch of questions. I spent at least 4 hours (I write slowly) preparing a response to explain that most of your concerns were things that I've already been thinking about (and to share my thoughts on them) and to suggest solutions for many of your concerns. You replied with an implicit, and then an explicit "TL;DR". That made me feel a bit disrespected.

I'm sorry for lashing out.

**Comment by jchodera** [comment]
I should be the one apologizing for not being able to fully digest the material you write here, but time is very limited and broken into small chunks. This makes it essentially impossible for me to be fully engaged when even reading a single comment or PR discussion takes a decent chunk of time. I hope this doesn't come off as too negative, but instead provides the perspective of someone who is very busy but interested in doing something with the code. Taking a stab at the notebooks, I has no idea what was going on, so wanted to pass on suggestions about how we could prevent a larger interestes audience from being quickly disengaged.

I love the idea of the book, but I would recommend we really think about "what can we do to make it simple for someone to jump in and do something they are interested in without having them become disengaged after a few minutes. That may be the best way to build some momentum for a user group outside you and JHP.

Definitely want the examples to be *reproducible* but maybe notebooks are not the best way. Will point you to an example that may work better in a moment.

**Comment by dwhswenson** [comment]
> I should be the one apologizing for not being able to fully digest the material you write here, but time is very limited and broken into small chunks.

No worries, and I do get that your time is limited -- and right now, things are running smoothly enough with the code that I'm able to produce a lot of results very quickly. It makes it that much harder to explain it all concisely!

> Taking a stab at the notebooks, I has no idea what was going on, so wanted to pass on suggestions about how we could prevent a larger interestes audience from being quickly disengaged.

Is this also a problem for the toy example (e.g., MSTIS sequence) notebooks? That's where I expected people to start. Each of those notebooks even includes a "list of tasks covered in this notebook" at the beginning. They're also more practical for interactive usage.

> but I would recommend we really think about "what can we do to make it simple for someone to jump in and do something they are interested in without having them become disengaged after a few minutes.

What defines "something they are interested in"? Again, are the toy models sufficient?

If so, that's where I would suggest starting. I didn't add any commentary in the "simplest TPS" examples because I really wanted to emphasize how incredibly simple they are. However, I can add some commentary if you'd like (shift some discussion from the MSTIS setup to the TPS version).

This is also the reason these are in that order in the ipynb directory's README. I assume people will start at the top.

***

Also: I've added a lot of commentary to the analysis notebook in this PR, which is the main part of the stuff here that is actually new, and also involves some techniques that seemed a little tricky to me. The last section is still in progress (code and comments) but there are some nice tricks in there, and OPS makes them very easy to implement.

We may want to split the analysis into multiple notebooks for pedagogic reasons: some of what I'm doing in there gets pretty advanced pretty fast.

**Comment by dwhswenson** [comment]
This is ready for review. There’s still more to do, but I wanted this example to be more generally available, so I'd rather have it reviewed now.

I added a little bit of commentary; could add more later. The main areas with significant discussion are the ones where things get a bit complicated.

Overall, this covers both flexible and fixed length TPS, and the resulting analysis. The analysis eventually gets into some pretty deep and situation-specific things -- these examples should be shown somewhere, but it might be better to put them in a separate file.

Things left to do:

* Split into subdirectories (I’ll open an issue on that soon)
* Path density plots
* Better (clearer, but equivalent) approach to the transition-type analysis
* Possibly split analysis into multiple files (beginners, advanced) and reorder some parts
* Simplify the temperature analysis. In particular, obtaining the number of dofs from OpenMM should be wrapped into something easy.

**Comment by jhprinz** [comment]
looks good. We can add more later.

**Pull request merged**
