### PR TITLE
[WIP] Shoot and Extend

### PR DESCRIPTION
**Pull request by jhprinz**
Solves making a general ExtendByShooting Mover still missing from PR #251.

Forward and Backward, Shooting and Extending is basically now one mover.

### CODE REVIEW

**Comment by jhprinz** [comment]
I would wait with this one after merge of PR #272 .

**Comment by jhprinz** [comment]
This is a VERy old PR. Maybe we will close this and redo it at a later stage. All it does is doing some restructuring to turn the Shooting Moves into one move and after all the changes we have made I fear that trying to fix this will cause more trouble than just redoing it after we have done the major changes.

It is only to make the code more reusable but will not add features or change the API.

**Comment by dwhswenson** [comment]
Given that this PR is sort of dead, how about I do this as part of the pathmover overhaul I'm about to start? The point is that this would give a superclass to contain all the detailed balance stuff I'll be adding, so that code doesn't have to be repeated in the convenience subclasses.

**Comment by dwhswenson** [comment]
(In other words, unless you disagree, let's close this without merging)

**Comment by jhprinz** [comment]
Yes, please do so. I was not so happy with my implementation anyway and fixing this will take longer than doing it from scratch!

**Pull request closed without merging**
