### PR TITLE
update reversal test for snapshots

### PR DESCRIPTION
**Pull request by jhprinz**
This should repair the bug in #456 and make sure that reversed snapshots will not be stored twice in specific cases.

This add

1. a check that will abort saving when the reversed copy is saved
2. improve saving of lazy loaded objects across multiple files

It will not solve all potential problems. Some of them will be address once objects are references using UUIDs.

### CODE REVIEW

**Comment by jhprinz** [comment]
That should do it. Let's see if tests pass...

**Comment by dwhswenson** [comment]
Could you add an explicit nosetest for the process that you described as causing the error? That is, something the does exactly the steps you outlined in https://github.com/choderalab/openpathsampling/issues/456#issuecomment-203459562 and ensures that we get the right behavior?

That way we have a check that we don't accidentally regress into this bug again.

**Comment by jhprinz** [comment]
Added testing. Should be fine after it passes tests.

**Comment by dwhswenson** [comment]
Perfect! That for the fix -- makes the "committor" analysis much more broadly useful. Merging!

**Pull request merged**
