### PR TITLE
[WIP] Store Engine with PathMover

### PR DESCRIPTION
**Pull request by jhprinz**
This will store the engine explicitly with a PathMover. It will not make any direct changes. Only that to set the default behaviour you need to set
```
paths.EngineMover.default_engine = ...
```
this used to be `.engine`, but was only used in `alanine.ipynb` anyway.
When you create an engine it will be set as default already and hence all PathMover created after that will use that engine. You can also specify your own engine as an optinal parameter for all PathMovers that use an engine (shooters, extenders and minus)

### CODE REVIEW

**Comment by jhprinz** [comment]
I removed the test in minusmover since the way we create movers this cannot happen. It uses either the default or the explicitely set engine for both shooters.

**Comment by jhprinz** [comment]
This is ready for review and merge, when it passes.

**Comment by dwhswenson** [comment]
in meeting. Have different approach. Hold onthis.

**Comment by jhprinz** [comment]
Sure, was a quick attempt. I can only work on this tomorrow... No time today...

**Comment by jhprinz** [comment]
I think this was adressed by #465 ? Can we close this now?

**Comment by dwhswenson** [comment]
Haha -- funny enough, I think I even changed my original `EngineMover.engine` to `EngineMover.default_engine` because of some potential confusion I found.

Main difference is that I don't automatically set default: only if you use certain simulations. `PathSampling`, in particular, has no default and requires the engine to be set on any engines that use it.

(I think I'd said at one point in a Skype call "nevermind on the hold: it's close enough to what I was thinking" -- and obviously, we ended up in the same place.)

Yep, #465 definitely duplicated this (and extended it a bit). Closing.

**Pull request closed without merging**
