### PR TITLE
Rename Orderparameter [rename merge no. #3]

### PR DESCRIPTION
**Pull request by jhprinz**
Orderparameter is changed to CollectiveVariable

### CODE REVIEW

**Comment by jhprinz** [comment]
if it passes this is ready to be merged after rename calculation.

**Comment by jhprinz** [comment]
Ready to be inspected.

**Comment by jhprinz** [comment]
This has now the corrections in it from wrong calculation changes.

**Comment by dwhswenson** [comment]
A few small changes where we really do mean specifically `orderparameter` and not general `collectivevariable`:

* `tis_analysis.py` everything except `OP_Function`->`CV_Function` on l. 24 should be reverted (the order parameter in here is the real TIS order parameter)

The rest are just a result of changing the above:

* `toy_analysis.ipynb` l. 133
* `toy_bootstrapping.ipynb` l. 286
* `toy_tis.ipynb` l.192, 261

**Comment by jhprinz** [comment]
Removed the toy_storage.ipynb which is indeed redundant and was only used for testing at some point.

**Comment by jhprinz** [comment]
This should be ready to merge. Just added the latest PR.

**Pull request merged**
