### PR TITLE
Details of MD5 failues in conda install

### PR DESCRIPTION
**Pull request by dwhswenson**
Right now, miniconda's MD5 doesn't match the value that Travis is seeing. 

I suspect this is a bug on the part of the folks at conda. It fails for me with both [OPS](https://travis-ci.org/choderalab/openpathsampling/builds/119608319) and nightly build on [dynamiq-md](https://travis-ci.org/dynamiq-md/dynamiq_engine/builds/119605522), both failing again after re-running, so I assume this is a bug and not a fluke.

This PR just adds a little more information of "expected" and "found" after an MD5 mismatch in the miniconda setup. Potentially useful debug info that probably should make its way elsewhere.

### CODE REVIEW

**Comment by dwhswenson** [comment]
Interesting... current expected is blank. So that will be a problem....

**Comment by dwhswenson** [comment]
Looks like the most recent version of Miniconda changed the name to `Miniconda2-latest-Linux-x86_64.sh`. However, `Miniconda-latest-Linux-x86_64.sh` still pulled down an old version (`Miniconda2-3.19.0-Linux-x86_64.sh`) -- we matched the MD5 for that one.

**Comment by dwhswenson** [comment]
The fact that this even gets into the proper tests means the bug is fixed. I'll re-run it'll it officially beats any stochastic errors, but this should be merged ASAP.

**Comment by jhprinz** [comment]
Agreed!

**Pull request merged**
