### PR TITLE
[WIP] Fast PathMoveChange loading...

### PR DESCRIPTION
**Pull request by jhprinz**
This PR will change the way `PathMoveChange`s are stored. This will allow much faster loading.

The store will now save a PMC by directly storing attributes in table and not use JSON except for details.
Each PMC now has the following attributes and we should think about good names for these:
```
.mover # this is a reference to the used mover
.subchanges # used by all node changes to store the subPMCs
.generated # list of all samples generated in this move. Only for SamplePMC
.details # all the rest that is specific to a move
```

more details coming

### CODE REVIEW

**Comment by dwhswenson** [comment]
Regarding names, I think most of those are good. The only one I would definitely suggest changing would be `generated`, which isn't clear on its own. `generated_samples`, maybe?

If we change the name of `PathMoveChange` (it is a bit unwieldy) then obviously `subchange` might also need adjustment, but it works for now. I think `mover` and `details` are quite clear.

Is the whole of `details` stored as JSON, or just parts? In principle, there are a few details which *all* PMCs will have (`accepted` is the first that comes to mind; `trials` (pointing to a list of `Sample`s) is another one). It might be nice to make these load faster than JSON requests would.

Definitely looking forward to the faster loading; but looping over all moves: what will be the way to do that? I assume it is no longer `for pmc in storage.pathmovechanges` (since I assume these are now each sub-pmc saved individually). We talked about adding some sort of `MCStep` (or `MCCycle` if you prefer) object (see #244) -- I think that's no more than a container for `SampleSet` and `PathMoveChange`, and each new step is made in the `PathSimulator` object. Should that be part of this PR?

**Comment by dwhswenson** [comment]
Oh, and please make appropriate modifications to the analysis stuff. For a couple reasons (mainly that my WHAM script fails if input data is insufficient) we haven't added `toy_analysis.ipynb` to the test suite. I suspect this may cause problems for a few parts of that -- let me know if you need help fixing those problems.

**Comment by jhprinz** [comment]
Will be resolved also by #251

**Comment by jhprinz** [comment]
Should have been closed by #251 and is already solved.

**Pull request closed without merging**
