### PR TITLE
Docs cleanup

### PR DESCRIPTION
**Pull request by dwhswenson**
Mostly cleaning up class docstrings to have a decent brief version. Also some other little cleanup of the documentation rst files.

This is sort of a "merge-at-will" thing: I'll keep working on it, but, @jhprinz, if you think the docstring changes will start to create conflicts with stuff you're working on, then merge this in at any time.

Starts on #151.

### CODE REVIEW

**Comment by dwhswenson** [comment]
I'll list a few more significant changes as I make them. In the first batch of commits, I: 

* removed `core.rst` (which was a copy of `ensemble.rst`)
* rearranged `pathmover.rst` to have sections that sense to me; organizing movers first by what they change about the sample (trajectory, ensemble, replica ID), then including movers that combine other movers, then including pre-made combinations

**Comment by jhprinz** [comment]
Good work so far. I think I will merge this when I have finished the path mover thing and focus on documentation. If you want to merge sooner, don't ask. just merge.

**Comment by jhprinz** [comment]
I would like to merge this into master to see the changes directly and go from there. I had some changes in path mover, move path, samples etc... I think there is no harm in pulling this into master.

**Comment by jhprinz** [comment]
Merging.

**Pull request merged**
