### PR TITLE
Refactor: Rename [1]

### PR DESCRIPTION
**Pull request by jhprinz**
This will do first part of renaming. I will split this into several (hopefully orthogonal) PRs.

- [x] `.atoms` to `.n_atoms` to be conform with mdtraj

### CODE REVIEW

**Comment by dwhswenson** [comment]
Confused:

1. The checkbox for renaming is marked complete, although this doesn't seem to include a completed rename to `n_atoms` (in fact, no changes even include "atom").
2. The last commit, which says it renames to `n_atoms`, actually only includes a permissions change.

I assume therefore that this is still WIP and that the things above were accidents? (Or maybe some changes were made but not committed as expected in the last commit?)

**Comment by dwhswenson** [comment]
Apparently I already did the rename to `n_atoms` in #160? 

I have a terrible habit of forgetting what code I've already written.

**Comment by jhprinz** [comment]
Yes, I realized that and then my internet connection on the train broke... So the rest was missing :)

**Comment by jhprinz** [comment]
This is meant to be merges after the Retis stuff!

**Comment by jhprinz** [comment]
THis is obsolete and contained in #192 .

**Pull request closed without merging**
