### PR TITLE
Fix Miscellaneous ipynbs

### PR DESCRIPTION
**Pull request by dwhswenson**
Several of the example ipynbs (that aren’t part of regular testing) have been broken by recent (and some not-so-recent) updates to the code. I’m fixing them so they run correctly.

- [x] `langevin_integrator_check.ipynb`
- [x] `move_strategies_and_schemes.ipynb`
- [x] `sequential_ensembles.ipynb`
- [x] `sliced_sequential_ensemble.ipynb`
- [x] `tutorial_visualization.ipynb` (partial: see #447)
- [x] `storage_mem_test.ipynb` (partial: see #447)
- [x] `which_network.ipynb` (incomplete notebook: removed from `localtest.sh`)

Just a bit of code rot we’ve had over time. We should remember to do this occasionally (and certainly before release!)

### CODE REVIEW

**Comment by dwhswenson** [comment]
@jhprinz : `storage_mem_test.ipynb` uses `OpenMMRandomEngine`. I don't see `OpenMMRandomEngine` (or any kind of `RandomEngine`) anywhere in the code. What should I do with that?

**Comment by jhprinz** [comment]
It is called RandomMDEngine and is part of `test_helpers.py` now. I renamed it at some point since it is not OpenMM specific. It used to use the Snapshots.

**Comment by dwhswenson** [comment]
Thanks. I'm going to parts of `tutorial_visualization.ipynb` and `storage_mem_test.ipynb` unfixed: there didn't seem to be an easy fix, and since I'm not sure what your intent was at the point that the bug occurs, I think it makes more sense for you to fix. Posting an issue on that in just a moment.

I suspect those will be easy for you: at least, the rest of this wasn't too bad for me to fix.

**Comment by dwhswenson** [comment]
Passed tests: ready to merge.

**Comment by jhprinz** [comment]
Very good! Merging...

**Pull request merged**
