### PR TITLE
Rename n [rename merge no. #1]

### PR DESCRIPTION
**Pull request by jhprinz**
- [x] Rename everything that as todo with numbers.
I have also changed that mostly
- [x]  `len()` is used instead of `n_snapshots`, etc... which is more pythonic and also mdtraj allows this `len(traj) == traj.n_frames`
- [x] AllIn, AllOut, etc...
- [x] Union, Intersection, etc...

### CODE REVIEW

**Comment by jhprinz** [comment]
Should be ready to merge. The only thing is that loading by string only works with the .uid property and not the name anymore. That is the downside. We might think about this but still, the name is not unique and not so suitable for loading.

**Comment by jhprinz** [comment]
fixes conflicts in notebooks. Can be merged now!

**Comment by dwhswenson** [comment]
One question: didn't we want to keep the `X` indicating a volume? I think that is clearer. `AllInEnsemble` isn't clearly a volume ensemble; it could be all the trajectories that are in some ensemble. So I think `AllInXEnsemble` to be brief or the more long-winded `AllInVolumeEnsemble` would be clearer.

**Comment by jhprinz** [comment]
Sure. I like both so I changed it. Should pass now.

**Comment by dwhswenson** [comment]
Merging, although `ensemble.rst` needs to be changed to `InX` from `InXX` now :-)

**Pull request merged**
