### PR TITLE
`is_canonical` flag

### PR DESCRIPTION
**Pull request by dwhswenson**
Handles the `is_canonical` part of #280. See discussion in there. Will *not* include the `submovers`/`movers` stuff also discussed in that issue.

- [x] Add `is_canonical` property to `PathMover`s; including usage in Minus
- [x] Add support for `is_canonical` flag in `PathMoveChange.canonical`
- [x] Tests for property in `testpathmover`
- [x] Tests for `PathMoveChange.canonical`

### CODE REVIEW

**Comment by dwhswenson** [comment]
Passed tests. This is ready for review and merge.

**Comment by jhprinz** [comment]
looks good. Feeld free to merge. Not sure if this will break #275. So we might merge the renaming first.

**Comment by dwhswenson** [comment]
I'll merge #275 first. This shouldn't break anything in that (it really is just adding a few lines; I think that more than half this PR is the additional tests.)

**Comment by jhprinz** [comment]
All right. Then I will merge this now.

**Pull request merged**
