### PR TITLE
Partial RETIS (part 2)

### PR DESCRIPTION
**Pull request by dwhswenson**
This is another merge of stuff from my `retis_transition` branch, mainly so it will be available to everyone before I leave for Scotland (i.e., @jhprinz so he can start running stuff and @bolhuis so he has something that works to play with and hopefully brag a little about to others in Edinburgh!)

Still missing are move-based analysis functions, but the `toy_tis.ipynb` and `toy_analysis.ipynb` are starting to look like what I think we want. My suggestion is to hold off merging for a bit: I assume I can add the renaming stuff into this before I leave, and I hope we might even finish the SequentialEnsemble scaling problem from #204 and #206.

Unique contents are basically correct usage of only the `Sample`s from `SampleSet`s for crossing probability calculation (didn't matter until minus move was included) and several simplifications in the ipynbs where I'd previously used the notebook to test things out before those complications were folded into a simple function in OPS (e.g., rebuilding from storage, and some common analysis that got reduced to one-liners).

### CODE REVIEW

**Comment by jhprinz** [comment]
Great. Let me know, when this is ready to merge. This will be very useful!

**Comment by dwhswenson** [comment]
What was I thinking when I said to hold off on merging? Of course this can be merged right now. I'd still like to make it our goal to finish the renaming stuff today, but that can be merged into master after this instead of before this.

I'm doubting that I'll finish #204 before I leave: that has more to do with all the other things that are on my "must do before I leave for a week" list than anything else, although I'm also restructuring the caching I'm adding there to be more generally useful. I hope to finish it up in corners of spare time while in Scotland.

**Comment by jhprinz** [comment]
Should we merge this first? I can also pull this into the next `rename_cv` if that makes it easier and fix merge issues on my side. I assume right now there is again a problem with a notebook.

**Comment by dwhswenson** [comment]
Almost fixed; just re-running the ipynb in question to make sure it is clean

**Comment by jhprinz** [comment]
Great. I will merge this as soon it is ready.

**Comment by dwhswenson** [comment]
In principle this should be ready for merge (assuming it passes tests).

**Comment by jhprinz** [comment]
Merging now.

**Pull request merged**
