### PR TITLE
Newpackagename openpathsampling

### PR DESCRIPTION
**Pull request by jhprinz**
This renames everything to use openpathsampling. Hope I did not forget anything...

### CODE REVIEW

**Comment by dwhswenson** [comment]
5 minutes of your time (maybe less):

Can you merge `upstream/master` into this? I'm pretty sure the only merge conflict is with a change I made in `.travis.yml` which will (1) fix the fact that this doesn't pass travis tests, and (2) make this automatically mergeable. 

Also, it is one line of disagreement: this is a quick fix, and I'd like to get this major change merged as my own stuff starts to diverge from master.

**Comment by jhprinz** [comment]
Sure

**Comment by jhprinz** [comment]
This should do it. My tests ran fine.

**Comment by jhprinz** [comment]
Checked nosetests and ipython notebooks, which all run fine now.
Only problem is the (probably backward shooting) see #141

**Comment by jhprinz** [comment]
forgot alanine :) which was still using opens

**Comment by jhprinz** [comment]
This is ready for review and merge!

**Pull request merged**
