### PR TITLE
[WIP] Longer documentation

### PR DESCRIPTION
**Pull request by dwhswenson**
Things I've been working on for documentation (for a while now). Mostly aimed for the PhD and MS students who may be using this in the future.

Creating the PR so you can see what I'm working on, and not duplicate efforts.

### CODE REVIEW

**Comment by jhprinz** [comment]
What about using something like the last .png as the logo? This looks pretty cool?

**Comment by jhprinz** [comment]
What is the status of this? Does it make sense to merge at some point?

**Comment by dwhswenson** [comment]
Since this is just docs beyond the in-code docs, it can be merged whenever and updated whenever. It shouldn't cause any conflicts.

Merged or not, the important thing is that you should know what explanations I'm already writing, so we don't duplicate effort.

**Comment by dwhswenson** [comment]
Let's go ahead and merge this -- I can always continue the branch in a new PR. 

This mainly includes some longer documentation stuff. It also includes some fixes so the docs will compile: we've removed/renamed some of the notebooks, and we hadn't updated that in docs. This fixes that.

New docs in this PR are only partially written, but partially written docs won't break anything.

**Comment by jhprinz** [comment]
merging...

**Pull request merged**
